basic/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^documentation/$', views.DocumentationTemplateView.as_view(), name='documentation'),
)

boards/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.BoardsView.as_view(), name='boards'),
    url(r'^show/(?P<pk>\d+)/$', views.ShowBoardView.as_view(), name='show_board'),
    url(r'^more/card/update/$', views.MoreOptionsView.as_view(), name='update_more_options'),
    url(r'^more/(?P<pk>\d+)/$', views.MoreOptionsView.as_view(), name='more_options'),
    url(r'^subtasks/edit/(?P<pk>\d+)/$', views.TaskUpdateView.as_view(), name='task_edit'),
    url(r'^subtasks/edit/$', views.TaskUpdateView.as_view(), name='task_edit'),
    url(r'^subtasks/delete/$', views.TaskDeleteView.as_view(), name='task_delete'),
    url(r'^subtasks/(?P<card_id>\d+)/create/$', views.TaskCreateView.as_view(), name='task_create'),
    url(r'^create/$', views.CreateBoardView.as_view(), name='createBoard'),
    url(r'^copy_board/$', views.CopyBoardView.as_view(), name='copy_board'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditBoardView.as_view(), name='editBoard'),
    url(r'^edit/rename/$', views.EditBoardView.as_view(), name='rename_board'),
    url(r'^columns/(?P<board_id>\d+)/create/$', views.ColumnCreateView.as_view(),
        name='create_column'),
    url(r'^columns/(?P<pk>\d+)/delete/$', views.ColumnDeleteView.as_view(),
        name='delete_column'),
    url(r'^columns/(?P<pk>\d+)/update/$', views.ColumnEditView.as_view(),
        name='edit_column'),
    url(r'^columns/column/update/$', views.ColumnEditView.as_view(),
        name='update_column'),
    url(r'^columns/attributes/update/$', views.SetColumnsAttributesView.as_view(),
        name='update_attributes'),
    url(r'^notify_deadlines/(?P<pk>\d+)/$', views.SendNotificationsView.as_view(), name='send_notifications'),
    url(r'^columns/(?P<column_pk>\d+)/rules/(?P<rule_pk>\d+)/delete$', views.DeleteColumnRuleView.as_view(), name='delete_column_rule'),
    url(r'^columns/(?P<column_id>\d+)/rules/create', views.ColumnRuleCreateView.as_view(), name='create_column_rule'),
)

kanban/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from supervision.views import LoginView, LogoutView, HomeView
import settings

admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
    url(r'^', include('basic.urls', namespace='basic')),
    url(r'^$', HomeView.as_view(), name='first_page'),
    url(r'^boards/', include('boards.urls', namespace='boards')),
    url(r'^supervision/', include('supervision.urls', namespace='supervision')),
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^analytics/', include('analytics.urls', namespace='analytics')),
    url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

supervision/urls.py
from django.conf.urls import patterns, url

import views


urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='home'),
)

# <editor-fold desc="User view urls">
urlpatterns += patterns('',
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/active/(?P<is_active>(True|False))/$', views.UserListView.as_view(),
        name='user_list'),
    url(r'^users/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^users/create/$', views.UserCreateView.as_view(), name='user_create'),
    url(r'^users/(?P<pk>\d+)/update/$', views.UserUpdateView.as_view(), name='user_update'),
    url(r'^users/(?P<pk>\d+)/delete/$', views.UserDeleteView.as_view(), name='user_delete'),
)
# </editor-fold>

# <editor-fold desc="Project view urls">
urlpatterns += patterns('',
    url(r'^projects/$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^projects/active/(?P<is_active>(True|False))/$', views.ProjectListView.as_view(),
        name='project_list'),
    url(r'^projects/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
    url(r'^projects/create/$', views.ProjectCreateView.as_view(), name='project_create'),
    url(r'^projects/(?P<pk>\d+)/update/$', views.ProjectUpdateView.as_view(),
        name='project_update'),
)
# </editor-fold>

# <editor-fold desc="Card view urls">
urlpatterns += patterns('',
    url(r'^cards/$', views.CardListView.as_view(), name='card_list'),
    url(r'^cards/active/(?P<is_active>(True|False))/$', views.CardListView.as_view(),
        name='card_list'),
    url(r'^cards/(?P<pk>\d+)/$', views.CardDetailView.as_view(), name='card_detail'),
    url(r'^cards/create/$', views.CardCreateView.as_view(), name='card_create'),
    url(r'^cards/(?P<pk>\d+)/update/$', views.CardUpdateView.as_view(), name='card_update'),
    url(r'^cards/(?P<pk>\d+)/delete/$', views.DeleteCardUpdateView.as_view(), name='card_delete'),
    url(r'^cards/move/(?P<pk>\d+)/$', views.MoveCardUpdateView.as_view(), name='card_move'),
)
# </editor-fold>

# <editor-fold desc="Team view urls">
urlpatterns += patterns('',
    url(r'^teams/$', views.TeamListView.as_view(), name='team_list'),
    url(r'^teams/active/(?P<is_active>(True|False))/$', views.TeamListView.as_view(),
        name='team_list'),
    url(r'^teams/(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^teams/create/$', views.TeamCreateView.as_view(), name='team_create'),
    url(r'^teams/(?P<pk>\d+)/update/$', views.TeamUpdateView.as_view(), name='team_update'),
)
# </editor-fold>

boards/views.py
import json
import datetime
from copy import deepcopy

from django.views.generic import View, TemplateView, ListView, CreateView
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Q

from braces.views import LoginRequiredMixin, CsrfExemptMixin
from django.views.generic.edit import UpdateView
from boards.forms import ColumnMoveRuleForm, TaskForm

from .models import Board, Project, Column, Card, Team, User, CardHistory, MoveColumnRule, Task
from .forms import ColumnForm

from boards.config import GROUP_PRODUCT_OWNER, GROUP_KANBAN_MASTER,\
    GROUP_ADMINISTRATOR, GROUP_DEVELOPER

from boards.management.tasks.generate_notice import check_expired_cards

DEFAULT_CRITICAL_CARD_THRESHOLD = -1


class BoardsView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        boards_kanban = []

        if user.can_be_admin:
            data = [{'board': b, 'kanbanmaster': False} for b in Board.objects.all()]
        else:
            teams_kanban = user.team_set.filter(userteam__group__name=GROUP_KANBAN_MASTER)
            #teams_other = user.team_set.exclude(userteam__group__name=GROUP_KANBAN_MASTER)
            ROLES = [GROUP_ADMINISTRATOR, GROUP_DEVELOPER, GROUP_PRODUCT_OWNER]
            teams_other = []
            for role in ROLES:
                teams = list(user.team_set.filter(userteam__group__name=role))
                for team in teams:
                    teams_other.append(team)

            # TODO: Check if board is active something like this
            # boards_kanban = list(self._get_team_boards(teams_kanban).filter(is_active=True))
            boards_kanban = list(self._get_team_boards(teams_kanban))

            # -------------
            my_boards = list(Board.objects.filter(is_active=True, author=user))
            boards_kanban = set(boards_kanban)
            for board in my_boards:
                boards_kanban.add(board)
            boards_kanban = list(boards_kanban)
            # -------------

            # TODO: Check if board is active something like this
            # boards_other = list(self._get_team_boards(teams_other)).filter(is_active=True))
            boards_other = list(self._get_team_boards(teams_other))
            boards_other = [b for b in boards_other if b not in boards_kanban]

            data_kanban = [{'board': b, 'kanbanmaster': True} for b in boards_kanban]
            data_other = [{'board': b, 'kanbanmaster': False} for b in boards_other]
            data = sorted(data_kanban + data_other, key=lambda el: el['board'].name.upper())

        params = {'data': data, 'exist_kanbanmaster': boards_kanban != []}
        return render(request, 'boards/boards.html', params)

    def _get_team_boards(self, team):
        projects = Project.objects.filter(team__in=team).distinct()
        return Board.objects.filter(project__in=projects).distinct()


class CreateBoardView(CsrfExemptMixin, LoginRequiredMixin, View):
    def post(self, request):
        table_name = request.POST['board_name']
        if Board.objects.filter(name=table_name, is_active=True).count() == 0:
            board = Board(name=table_name)
            board.author = request.user
            board.save()
            return render(request, 'boards/editBoard.html', {'board': board})
        else:
            #board already exist
            boards = Board.objects.filter(is_active='True')
            return render(request, 'boards/boards.html',
                          {'boards': boards, 'error_board_exist': True})
        """
        elif Board.objects.filter(name=table_name, is_active=False).count() > 0:
            board = Board.objects.get(name=table_name, is_active=False)
            board.is_active = True
            board.save()
            return render(request, 'boards/editBoard.html', {'board': board, 'teams': teams})
        """


class EditBoardView(CsrfExemptMixin, LoginRequiredMixin, View):
    def get(self, request, pk):
        if pk is not None:
            board = Board.objects.get(id=pk)
        else:
            return render(request, 'boards/boards.html')

        if board is not None:
            cols_subcols = get_columns(board.id)
            attribute_columns = get_attribute_columns(board.id)
            selected_attributes = get_selected_attribute_columns(board.id)
            params = {'board': board, 'table_data': cols_subcols,
                      'attribute_columns': attribute_columns,
                      'selected_attributes': selected_attributes}
            return render(request, 'boards/editBoard.html', params)
        else:
            return render(request, 'boards/boards.html')

    def post(self, request):
        board_id = request.POST.get('board_id')
        new_name = request.POST.get('board_name')
        interval = request.POST.get('notice_interval')
        board = None
        if board_id and interval:
            board = get_object_or_404(Board, pk=board_id)
            board.notice_interval = interval
            board.save()
        if board_id and new_name:
            board = get_object_or_404(Board, pk=board_id)
            board.name = new_name
            board.save()
        if board is not None:
            cols_subcols = get_columns(board.id)
            attribute_columns = get_attribute_columns(board.id)
            selected_attributes = get_selected_attribute_columns(board.id)
            params = {'board': board, 'table_data': cols_subcols,
                      'attribute_columns': attribute_columns,
                      'selected_attributes': selected_attributes}
            return render(request, 'boards/editBoard.html', params)
        else:
            return render(request, 'boards/boards.html')


class ShowBoardView(CsrfExemptMixin, LoginRequiredMixin, View):
    def get(self, request, pk, critical_card_threshold=DEFAULT_CRITICAL_CARD_THRESHOLD,
            critical_card_error=False, form=None):
        user = request.user
        board = get_object_or_404(Board, pk=pk)
        table_data = None
        if board:
            table_data = get_columns(board.id)

        product_owner_or_kanban_master = []

        for project in board.project_set.filter(is_active=True):
            if user.is_kanban_master(project) or \
            user.is_product_owner(project):
                product_owner_or_kanban_master.append(project)

        done_columns = []
        if board.column_set.exists() and critical_card_threshold != 0:
            done_columns = [board.post_acceptance_columns.pop()]

        default_threshold = False
        if critical_card_threshold == DEFAULT_CRITICAL_CARD_THRESHOLD:
            default_threshold = True

        params = {
            'form': form,
            'table_data': table_data,
            'critical_card_threshold': critical_card_threshold,
            'default_threshold': default_threshold,
            'critical_card_error': critical_card_error,
            'end_boundary_and_after_columns': done_columns,
            'board': board,
            'project_kbm_po': product_owner_or_kanban_master,
            'projects': json.dumps([p.pk for p in board.project_set.filter(is_active=True)]),
        }
        return render(request, 'boards/show_board.html', params)

    def post(self, request, pk):
        num_of_days = request.POST['num_of_days']
        show_board = ShowBoardView()
        if num_of_days.isdigit():
            return show_board.get(request, pk=pk, critical_card_threshold=int(num_of_days))
        else:
            return show_board.get(request, pk=pk, critical_card_error=True)


class ShowColumnMixin(object):
    def get_context_data(self, **kwargs):
        context_data = super(ShowColumnMixin, self).get_context_data(**kwargs)
        context_data['board'] = Board.objects.get(pk=self.kwargs['board_id'])
        return context_data


class ColumnCreateView(LoginRequiredMixin, ShowColumnMixin, CreateView):
    model = Column
    form_class = ColumnForm
    template_name = 'boards/createColumn.html'

    def get_form_kwargs(self):
        kwargs = super(ColumnCreateView, self).get_form_kwargs()
        if kwargs.get('data') is not None:
            data = deepcopy(kwargs.get('data').dict())
            data.update({'board': self.kwargs["board_id"]})
            kwargs['data'] = data
        kwargs['board_id'] = self.kwargs['board_id']

        return kwargs


def get_column_children(parent_column_id):
    """
    From given column id function returns list of all children.
    """
    # find fist child
    column = Column.objects.filter(previous_column=None, parent_column_id=parent_column_id,
                                   is_active=True)
    columns = []
    if column:
        column = column[0]
        while column is not None:
            # append child and move to next column
            columns.append(column)
            column = column.next_column

    return columns


def get_columns(board_id):
    """
    Returns a list of dictionaries with keys column, children and number_of_cards.
    Column represents column object while children represents a list of objects(Column)
    which represent children.
    """
    # get first column on board
    column = Column.objects.filter(board=board_id, previous_column=None,
                                   parent_column=None, is_active=True)
    columns = []
    # if board have columns
    if column:
        column = column[0]

        while column is not None:
            children = []
            number_of_cards = 0
            # column have children
            if column.children.all():
                # get all children of column in proper order
                children = get_column_children(column.id)
                number_of_cards += get_number_of_cards(children)

            number_of_cards += len(column.card_set.filter(is_active=True))

            column_dictionary = {'column': column, 'children': children,

boards/templates/boards/boards.html
{% extends 'supervision/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h1 class="text-center">Boards</h1>
            </div>
        </div>
        {% if user.can_be_kanban_master %}
            <div class="text-right">
                <a href="{% url 'boards:copy_board' %}" id="copyTableButton">
                    <button type="button" class="btn btn-info">
                        Copy board</button>
                </a>
                <a href="#" id="createTableButton">
                    <button type="button" class="btn btn-primary">
                        <span class="glyphicon glyphicon-plus"></span> Create board</button>
                </a>
                {% if error_board_exist %}
                    <p style="color: RED">Board with this name already exists!</p>
                {% endif %}
                <p></p>
            </div>
        {% endif %}
        <div>
            {% if data %}
                <table class="table table-hover" data-link="row">
                    <thead>
                    <th>#</th>
                    <th>Board name</th>
                    {% if  exist_kanbanmaster %}
                        <th>Edit</th>
                        <th>Deadline Notification</th>
                    {% endif %}
                    </thead>
                    <tbody>
                    {% for element in data %}
                        <tr class='clickableRow' href="{% url "boards:show_board" pk=element.board.id %}">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ element.board.name }}</td>
                            {% if element.kanbanmaster %}
                                <td>
                                    <a href="{% url 'boards:editBoard' pk=element.board.id %}">
                                        <button class="btn btn-default btn-sm">Edit board</button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'boards:send_notifications' pk=element.board.id %}">
                                        <button class="btn btn-default btn-sm">Send</button>
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h3>There's no project tables.</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $("#createTableButton").click(function () {
                bootbox.prompt("Enter board name:", function (result) {
                    if (result) {
                        var form = $(document.createElement("form"));
                        var boardNameInput = $(document.createElement("input"));
                        form.attr("action", "{% url 'boards:createBoard' %}");
                        form.attr("method", "post");
                        boardNameInput.attr("value", result);
                        boardNameInput.attr("name", "board_name");
                        boardNameInput.attr("type", "hidden");
                        form.append(boardNameInput);
                        form.submit();
                    } else {

                    }
                });
            });

            $(".clickableRow").click(function () {
                window.document.location = $(this).attr("href");
            });
        });
    </script>
{% endblock %}

boards/templates/boards/create_task.html
{% extends 'boards/edit_task_base.html' %}

{% block title %}Create Task{% endblock %}
{% block submit %}Create{% endblock %}

boards/templates/boards/edit_column.html
{% extends 'supervision/base.html' %}

{% block content %}
    <div class="container">
    <h3>Edit column {{ column.name }}</h3>
        <form class="form-horizontal" role="form" action="{% url 'boards:update_column' %}"
              id="update_column_form" method="POST" >
            {% csrf_token %}
            <input type="hidden" name="column_id" value="{{ column.id }}">
            <div class="form-group">
                <label for="column_name" class="col-sm-2 control-label">Name</label>

                <div class="col-sm-3">
                    <input type="text" class="form-control" id="column_name"
                           name="name"
                           value="{% if column.name %}{{ column.name }}{% endif %}"/>
                </div>
            </div>
            <div class="form-group">
                <label for="column_wip" class="col-sm-2 control-label">WIP</label>

                <div class="col-sm-3">
                    <input type="number" class="form-control" id="column_wip"
                           name="wip"
                           value="{{ column.wip }}"/>
                </div>
                {% if error_child_wip %}
                <div class="has-errors error-font">
                    <label class="control-label">
                        Entered WIP was not valid. One of the cildren's column has larger WIP.
                    </label>
                </div>
                {% endif %}
                {% if error_parent_wip %}
                <div class="has-errors error-font">
                    <label class="control-label">
                        Entered WIP was not valid. Parent's column has lower WIP.
                    </label>
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="column_color" class="col-sm-2 control-label">Color</label>
                <div class="col-sm-3">
                    <input type="color" class="form-control" id="column_color"
                           name="color"
                           value="#{% if column.color %}{{ column.color }}{% else %}ffffff{% endif %}"/>
                </div>
            </div>
            <div class="form-group">
                <label for="column_next_column }}" class="col-sm-2 control-label">Next
                    column</label>

                <div class="col-sm-3">
                    <input type="text" disabled="disabled" class="form-control"
                           name="next" value="{{ column.next_column }}" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Parent column</label>

                <div class="col-sm-3">
                    <input type="text" disabled="disabled" class="form-control"
                           name="parent" value="{{ column.parent_column }}" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default"
                            id="updateColumnSubmitButton">Update</button>
                </div>
            </div>
            <br/><br/>
            {{ form.errors }}

            <div>
                <h3>Card Moving Rules</h3>

                <br />
                <br />

                {% if column.target_rules.count > 0 or column.origin_rules.count > 0 %}
                <table class="table table-responsive">
                    <tr>
                        <th class="col-md-2">Origin</th>
                        <th class="col-md-2">Target</th>
                        <th class="col-md-2">Group</th>
                        <th class="col-md-2"></th>
                    </tr>

                    {% for rule in column.origin_rules.all %}
                        {% if rule.is_active == True %}
                            <tr>
                                <td class="col-md-2">{{ rule.column_origin.name }}</td>
                                <td class="col-md-2">{{ rule.column_target.name }}</td>
                                <td class="col-md-2">{{ rule.user_group.name }}</td>
                                <td class="col-md-2">
                                    <a href="{% url 'boards:delete_column_rule' column_pk=column.pk rule_pk=rule.pk %}" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}

                    {% for rule in column.target_rules.all %}
                        {% if rule.is_active == True %}
                            <tr>
                                <td class="col-md-2">{{ rule.column_origin.name }}</td>
                                <td class="col-md-2">{{ rule.column_target.name }}</td>
                                <td class="col-md-2">{{ rule.user_group.name }}</td>
                                <td class="col-md-2">
                                    <a href="{% url 'boards:delete_column_rule' column_pk=column.pk rule_pk=rule.pk %}" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </table>
                {% else %}
                    <p class="col-md-offset-1">No rules defined.</p>
                {% endif %}

                <br />
                <a href="{% url 'boards:create_column_rule' column_id=column.pk %}" class="btn btn-primary">Create rule</a>
            </div>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#updateColumnSubmitButton').on('click', function (e, confirmed) {
                var w = $("#column_wip").val();
                if (w >= {{ column.card_count }}) {
                    $('#updateColumnSubmitButton').trigger('click', true);
                }
                var message = "This column already contains " +
                        {{ column.card_count }} + " cards. With lowering columns WIP violation " +
                        "is reached Do you want to continue?";
                if (!confirmed) {
                    e.preventDefault();
                    bootbox.confirm(message, function (response) {
                        if (response) {
                            $('#updateColumnSubmitButton').trigger('click', true);
                        }
                    });
                }
            });
        });
    </script>
{% endblock %}

boards/templates/boards/show_board_base.html
<td class="column-container">
    <ul class="list-unstyled list-group card-width rc{{ prev_counter }}{{ counter }} project-{{ project.pk }}"
        data-column-id="{{ column.pk }}">
        {% for card in cards %}
            {% if card.project == project and card.is_active %}
            <li data-card-id="{{ card.pk }}">
                <div class="list-group-item" style="background-color:
                        {% if card.deadline != None and not default_threshold and card.deadline_time <= critical_card_threshold  and card.column not in end_boundary_and_after_columns%}
                            {{ card.COLOR_DEADLINE }}
                        {% else %}
                            {{ card.color }}
                        {% endif %}">
                    {% if card.is_size %}
                        {% if card.size %}
                            <span class="badge">{{ card.size }}</span>
                        {% else %}
                            <span class="badge">0</span>
                        {% endif %}
                    {% endif %}
                    <h6 class="list-group-item-text card-description-size" style="text-align: left">
                        ID: {{ card.id }} <br/>
                        Assignee: <span class="glyphicon glyphicon-user"></span> {{ card.assignee }}
                    </h6>
                    <hr style="padding: 0px; margin-bottom: 4px; margin-top: 2px" />
                    <h4 class="list-group-item-heading card-title-size">{{ card.name }}</h4>
                    {% if card.is_priority %}
                        <h4 class="list-group-item-heading card-description-size">Priority: {{ card.get_priority_display }}</h4>
                    {% endif %}
                    {% if card.is_deadline %}
                    <h4 class="list-group-item-heading card-description-size">Deadline: {{ card.deadline }}</h4>
                    {% endif %}
                    <hr style="padding: 0px; margin-bottom: 4px; margin-top: 2px" />
                    <p class="list-group-item-text card-description-size">
                        <button class="btn btn-default btn-xs" onclick="location.href='{% url 'supervision:card_detail' pk=card.pk %}'" >
                            <span class="glyphicon glyphicon-zoom-in"></span>
                        </button>
                        <button class="btn btn-default btn-xs" onclick="location.href='{% url 'supervision:card_update' pk=card.pk %}'" >
                            <span class="glyphicon glyphicon-wrench"></span>
                        </button>
                        <button class="btn btn-default btn-xs delete_card_button" data-card-id="{{ card.pk }}">
                            <span class="glyphicon glyphicon-remove delete_card_button" data-card-id="{{ card.pk }}"></span>
                        </button>
                        <button class="btn btn-default btn-xs more_options" onclick="location.href='{% url 'boards:more_options' pk=card.pk %}'">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </button>
                    </p>
                </div>
            </li>
            {% endif %}
        {% endfor %}
        {# Needed in order to drag card to last place in column, otherwise it is dificuilt. #}
        <li><br /><br /><br /></li>
    </ul>
    <div class="column-name ct{{ prev_counter }}{{ counter }}" style="display:none" >
        {% for char in column.name %}
            <strong>{{ char }}</strong><br/>
        {% endfor %}
    </div>
</td>

boards/templates/boards/update_task.html
{% extends 'boards/edit_task_base.html' %}

{% block title %}Update Task{% endblock %}
{% block submit %}Update{% endblock %}