analytics/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.ChooseAnalyticsView.as_view(), name='choose'),
    url(r'^cumulative/choose$', views.CumulativeFlowView.as_view(), name='cumulative_choose'),
    url(r'^cumulative/board_selected$', views.CumulativeProjectsView.as_view(),
        name='cumulative_board_selected'),
    url(r'^cumulative/show$', views.CumulativeFlowView.as_view(), name='cumulative_show'),
    url(r'^wip_violations/choose$', views.WipViolationsView.as_view(), name='wip_choose'),
    url(r'^wip_violations/board_selected$', views.WipViolationsProjectsView.as_view(),
        name='wip_board_selected'),
    url(r'^wip_violations/show$', views.WipViolationsView.as_view(), name='wip_violations_show'),
    url(r'^dev_contribution/choose', views.DeveloperContributionView.as_view(), name='developer_contribution_choose'),
    url(r'^dev_contribution/show$', views.DeveloperContributionView.as_view(), name='developer_contribution'),
    url(r'^dev_contribution/board_selected$', views.DeveloperContributionProjectsView.as_view(),
        name='dev_contr_board_selected'),
    url(r'^average_lead_time/show$', views.AverageLeadTimeView.as_view(),
        name='average_lead_time_show'),
    url(r'^average_lead_time/choose$', views.AverageLeadTimeChooseView.as_view(),
        name='average_lead_time_choose'),
    url(r'^average_lead_time/choose_end$', views.AverageLeadTimeChooseEndView.as_view(),
        name='average_lead_time_choose_end'),
    url(r'^average_lead_time/board_selected$', views.AverageLeadTimeSelectView.as_view(),
        name='average_lead_time_selected'),
)

basic/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^documentation/$', views.DocumentationTemplateView.as_view(), name='documentation'),
)

boards/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.BoardsView.as_view(), name='boards'),
    url(r'^show/(?P<pk>\d+)/$', views.ShowBoardView.as_view(), name='show_board'),
    url(r'^more/card/update/$', views.MoreOptionsView.as_view(), name='update_more_options'),
    url(r'^more/(?P<pk>\d+)/$', views.MoreOptionsView.as_view(), name='more_options'),
    url(r'^subtasks/edit/(?P<pk>\d+)/$', views.TaskUpdateView.as_view(), name='task_edit'),
    url(r'^subtasks/edit/$', views.TaskUpdateView.as_view(), name='task_edit'),
    url(r'^subtasks/delete/$', views.TaskDeleteView.as_view(), name='task_delete'),
    url(r'^subtasks/(?P<card_id>\d+)/create/$', views.TaskCreateView.as_view(), name='task_create'),
    url(r'^create/$', views.CreateBoardView.as_view(), name='createBoard'),
    url(r'^copy_board/$', views.CopyBoardView.as_view(), name='copy_board'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditBoardView.as_view(), name='editBoard'),
    url(r'^edit/rename/$', views.EditBoardView.as_view(), name='rename_board'),
    url(r'^columns/(?P<board_id>\d+)/create/$', views.ColumnCreateView.as_view(),
        name='create_column'),
    url(r'^columns/(?P<pk>\d+)/delete/$', views.ColumnDeleteView.as_view(),
        name='delete_column'),
    url(r'^columns/(?P<pk>\d+)/update/$', views.ColumnEditView.as_view(),
        name='edit_column'),
    url(r'^columns/column/update/$', views.ColumnEditView.as_view(),
        name='update_column'),
    url(r'^columns/attributes/update/$', views.SetColumnsAttributesView.as_view(),
        name='update_attributes'),
    url(r'^notify_deadlines/(?P<pk>\d+)/$', views.SendNotificationsView.as_view(), name='send_notifications'),
    url(r'^columns/(?P<column_pk>\d+)/rules/(?P<rule_pk>\d+)/delete$', views.DeleteColumnRuleView.as_view(), name='delete_column_rule'),
    url(r'^columns/(?P<column_id>\d+)/rules/create', views.ColumnRuleCreateView.as_view(), name='create_column_rule'),
)

kanban/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from supervision.views import LoginView, LogoutView, HomeView
import settings

admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
    url(r'^', include('basic.urls', namespace='basic')),
    url(r'^$', HomeView.as_view(), name='first_page'),
    url(r'^boards/', include('boards.urls', namespace='boards')),
    url(r'^supervision/', include('supervision.urls', namespace='supervision')),
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^analytics/', include('analytics.urls', namespace='analytics')),
    url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

supervision/urls.py
from django.conf.urls import patterns, url

import views


urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='home'),
)

# <editor-fold desc="User view urls">
urlpatterns += patterns('',
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/active/(?P<is_active>(True|False))/$', views.UserListView.as_view(),
        name='user_list'),
    url(r'^users/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^users/create/$', views.UserCreateView.as_view(), name='user_create'),
    url(r'^users/(?P<pk>\d+)/update/$', views.UserUpdateView.as_view(), name='user_update'),
    url(r'^users/(?P<pk>\d+)/delete/$', views.UserDeleteView.as_view(), name='user_delete'),
)
# </editor-fold>

# <editor-fold desc="Project view urls">
urlpatterns += patterns('',
    url(r'^projects/$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^projects/active/(?P<is_active>(True|False))/$', views.ProjectListView.as_view(),
        name='project_list'),
    url(r'^projects/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
    url(r'^projects/create/$', views.ProjectCreateView.as_view(), name='project_create'),
    url(r'^projects/(?P<pk>\d+)/update/$', views.ProjectUpdateView.as_view(),
        name='project_update'),
)
# </editor-fold>

# <editor-fold desc="Card view urls">
urlpatterns += patterns('',
    url(r'^cards/$', views.CardListView.as_view(), name='card_list'),
    url(r'^cards/active/(?P<is_active>(True|False))/$', views.CardListView.as_view(),
        name='card_list'),
    url(r'^cards/(?P<pk>\d+)/$', views.CardDetailView.as_view(), name='card_detail'),
    url(r'^cards/create/$', views.CardCreateView.as_view(), name='card_create'),
    url(r'^cards/(?P<pk>\d+)/update/$', views.CardUpdateView.as_view(), name='card_update'),
    url(r'^cards/(?P<pk>\d+)/delete/$', views.DeleteCardUpdateView.as_view(), name='card_delete'),
    url(r'^cards/move/(?P<pk>\d+)/$', views.MoveCardUpdateView.as_view(), name='card_move'),
)
# </editor-fold>

# <editor-fold desc="Team view urls">
urlpatterns += patterns('',
    url(r'^teams/$', views.TeamListView.as_view(), name='team_list'),
    url(r'^teams/active/(?P<is_active>(True|False))/$', views.TeamListView.as_view(),
        name='team_list'),
    url(r'^teams/(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^teams/create/$', views.TeamCreateView.as_view(), name='team_create'),
    url(r'^teams/(?P<pk>\d+)/update/$', views.TeamUpdateView.as_view(), name='team_update'),
)
# </editor-fold>

supervision/models.py
from django.db import models

# Create your models here.

supervision/views/base.py
from django.http.response import HttpResponseRedirect
from django.http import Http404
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect

from braces.views import LoginRequiredMixin

from boards.config import GROUP_ADMINISTRATOR, GROUP_KANBAN_MASTER, GROUP_DEVELOPER, \
    GROUP_PRODUCT_OWNER
from boards.models import Project


class SetInactiveMixin(object):
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)


class FilterActiveMixin(object):
    def get_queryset(self):
        queryset = super(FilterActiveMixin, self).get_queryset()
        is_active = self.kwargs.get('is_active')

        if is_active is None:
            return queryset
        is_active = is_active == 'True'
        return queryset.filter(is_active=bool(is_active))


class NextPageMixin(object):
    def get_success_url(self):
        next_url = self.request.REQUEST.get('next')
        if next_url:
            return next_url

        return super(NextPageMixin, self).get_success_url()


class UserToFormKwargsMixin(object):
    def get_form_kwargs(self):
        kwargs = super(UserToFormKwargsMixin, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class PermissionsMixin(LoginRequiredMixin):
    """
    Checks, if logged in user is in required groups for provided project. Get project method has to
    be implemented, in order to retrieve project.
    This Mixin has to be the left most mixin in class based view (exception CsrfExemptMixin).
    """

    groups_required = []
    permission_denied_url = None

    def get_permission_denied_url(self):
        if not self.permission_denied_url:
            raise NotImplementedError('permission_denied_url_has_to_be_provided')

    def get_project(self):
        raise NotImplementedError('get_project method not implemented.')

    def get(self, request, *args, **kwargs):
        return self._validate() or super(PermissionsMixin, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self._validate() or super(PermissionsMixin, self).post(request, *args, **kwargs)

    def _validate(self):
        """Encapsulates validation in order not to repeat the code in get and post methods."""

        self._project = self.get_project()
        self._validate_input()

        # Checks if there are any queued messages.
        if self.request._messages._queued_messages:
            return redirect(self.get_permission_denied_url())

    def _validate_input(self):
        """
        If any addition permissions have to be checked, then this should be done in this method.
        """

        user, has_permission = self.request.user, False

        if GROUP_ADMINISTRATOR in self.groups_required:
            has_permission = has_permission or user.is_admin(self._project)
        if GROUP_KANBAN_MASTER in self.groups_required:
            has_permission = has_permission or user.is_kanban_master(self._project)
        if GROUP_PRODUCT_OWNER in self.groups_required:
            has_permission = has_permission or user.is_product_owner(self._project)
        if GROUP_DEVELOPER in self.groups_required:
            has_permission = has_permission or user.is_developer(self._project)

        if not has_permission:
            messages.info(self.request, 'Permission denied.')

supervision/views/cards.py
from django.http.response import Http404
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, CreateView, UpdateView

from .base import PermissionsMixin, FilterActiveMixin, UserToFormKwargsMixin
from ..forms import CardCreateModelForm, CardUpdateModelForm, CardDeleteModelForm, MoveCardModelForm
from boards.config import GROUP_PRODUCT_OWNER, GROUP_KANBAN_MASTER, GROUP_DEVELOPER
from boards.models import Card, Project
from boards.views import ShowBoardView, DEFAULT_CRITICAL_CARD_THRESHOLD


class CardAdminMixin(PermissionsMixin):
    """Checks if user has required permissions."""

    model = Card

    def get_project(self):
        if 'pk' in self.kwargs or 'slug' in self.kwargs:
            self.object = self.get_object()
            return self.object.project
        elif 'project_pk' in self.request.REQUEST:
            return get_object_or_404(Project, pk=self.request.REQUEST['project_pk'])
        else:
            raise Http404('Card or project id has to be provided.')

    def _validate_input(self):
        super(CardAdminMixin, self)._validate_input()

        if not self._project.board.has_columns:
            messages.info(self.request, "Project doesn't have active columns.")

    def get_permission_denied_url(self):
        return reverse('boards:show_board', args=(self._project.board.pk,))


class DataToFormKwargsMixin(UserToFormKwargsMixin):
    """Has to be placed left to ValidateInputMixin in order to have project."""

    def get_form_kwargs(self):
        kwargs = super(DataToFormKwargsMixin, self).get_form_kwargs()
        kwargs['project'] = self._project
        return kwargs


class CardDetailView(CardAdminMixin, DetailView):
    template_name = 'supervision/cards/detail.html'
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER, GROUP_DEVELOPER]


# Currently not used.
class CardListView(CardAdminMixin, FilterActiveMixin, ListView):
    template_name = 'supervision/cards/list.html'


class CardCreateView(CardAdminMixin, DataToFormKwargsMixin, CreateView):
    form_class = CardCreateModelForm
    template_name = 'supervision/cards/create.html'
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER]

    def _validate_input(self):
        """Kanban master adds cards to priority column, so it has to exist."""

        super(CardCreateView, self)._validate_input()
        if not self.request.user.is_kanban_master(self._project):
            return

        priority_column = self._project.board.priority_column
        if not priority_column:
            messages.info(self.request, 'Board doesnt have a priority column.')
        if priority_column.silver_bullet_cards.exists():
            messages.info(self.request, 'Priority column can only have 1 silver bullet card.')


class CardUpdateView(CardAdminMixin, DataToFormKwargsMixin, UpdateView):
    form_class = CardUpdateModelForm
    template_name = 'supervision/cards/update.html'
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER, GROUP_DEVELOPER]

    def _validate_input(self):
        super(CardUpdateView, self)._validate_input()

        self.object = self.get_object()
        if not self.object.can_update_card(self.request.user):
            messages.info(self.request, "You don't have permission to edit card in column "
                                        "%(column)s." % {'column': self.object.column})

    def get_form_kwargs(self):
        kwargs = super(CardUpdateView, self).get_form_kwargs()
        kwargs['card'] = self.object
        return kwargs


class DeleteCardUpdateView(CardAdminMixin, UserToFormKwargsMixin, UpdateView):
    form_class = CardDeleteModelForm
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER]

    def get(self, request, *args, **kwargs):
        raise Http404()

    def _validate_input(self):
        super(DeleteCardUpdateView, self)._validate_input()
        if not self.object.can_delete_card(self.request.user):
            messages.info(self.request, "You don't have permission to delete card.")
        if not self.object.is_active:
            messages.info(self.request, "Card is already deleted.")


class MoveCardUpdateView(CardAdminMixin, DataToFormKwargsMixin, UpdateView):
    form_class = MoveCardModelForm
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER, GROUP_DEVELOPER]

    def get(self, request, *args, **kwargs):
        raise Http404()

    def form_invalid(self, form):
        return ShowBoardView().get(self.request, self.object.column.board.pk,
                                   critical_card_threshold=DEFAULT_CRITICAL_CARD_THRESHOLD,
                                   critical_card_error=False, form=form)

    def get_form_kwargs(self):
        kwargs = super(MoveCardUpdateView, self).get_form_kwargs()
        kwargs['card'] = self.object
        return kwargs

supervision/views/general.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from django.views.generic import View, TemplateView
from braces.views import LoginRequiredMixin

from supervision.forms.general import LoginForm


class LoginView(View):
    """
    View for login. Request parameter 'next' can contain the next page to render after login.
    """

    def get(self, request):
        if not request.user.is_authenticated():
            return render(request, 'supervision/login.html', {'form': LoginForm()})
        return render(request, 'supervision/home.html')

    def post(self, request):
        if not request.user.is_authenticated():
            form = LoginForm(data=request.POST)
            if form.is_valid():
                form.login_user(request)
            else:
                messages.warning(request, form.formatted_error)

        return redirect(request.REQUEST.get('next') or reverse('supervision:home'))


class LogoutView(View):
    """
    View for logout. Request parameter 'next' can contain the next page to render after logout.
    """

    def get(self, request):
        logout(request)
        return redirect(request.REQUEST.get('next') or reverse('supervision:home'))


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'supervision/home.html'


class ErrorView(LoginRequiredMixin, TemplateView):
    template_name = 'supervision/error.html'

supervision/templates/supervision/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    {% load dajaxice_templatetags %}
    <head>
        <script src="{% static 'supervision/js/jquery-1.11.0.min.js' %}"></script>
        <script src="{% static 'supervision/js/jquery.dajax.core.js' %}"></script>
        <script src="{% static 'supervision/bootstrap/3.1.1/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'supervision/bootstrap/bootbox/bootbox.min.js' %}"></script>
        <script src="{% static 'supervision/js/jquery.ba-serializeobject.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'supervision/bootstrap/3.1.1/css/bootstrap-theme.min.css' %}" />
        <link rel="stylesheet" href="{% static 'supervision/bootstrap/3.1.1/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'supervision/css/style.css' %}" />
        {% dajaxice_js_import %}
        <title></title>
    </head>
    <body>
        <header id="top" class="navbar navbar-static-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-target=".bs-navbar-collapse" data-toggle="collapse" type="button"></button>
                    <a href="{% url 'supervision:home' %}" class="navbar-brand">Kanban-tool</a>
                </div>
                <nav class="collapse navbar-collapse" role="navigation">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'supervision:team_list' %}">Teams</a>
                        </li>
                        {% if user.can_be_kanban_master %}
                        <li>
                            <a href="{% url 'supervision:project_list' is_active=True %}">Projects</a>
                        </li>
                        {% endif %}
                        {% if user.can_be_admin %}
                        <li>
                            <a href="{% url 'supervision:user_list' is_active=True %}">Users</a>
                        </li>
                        {% endif %}
                        <li>
                            <a href="{% url 'boards:boards' %}">Boards</a>
                        </li>
                        <li>
                            <a href="{% url 'analytics:choose' %}">Analytics</a>
                        </li>
                        {% comment %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                        {% endcomment %}
                        <li>
                            <a href="{% url 'basic:documentation' %}">Documentation</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li>
                            <a href="#">{{ user.email }}</a>
                        </li>
                        <li><a href="{% url 'logout' %}">log out</a></li>
                        {% else %}
                            <li>
                                <a href="{% url 'login' %}">Log in</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <hr class="horizontal-line-custom" />
        </header>
        <div id="content">
            {% block base_messages %}
                {% if messages %}
                <div id="message-modal" class="modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h2 class="modal-title">Alert</h2>
                            </div>
                            <div class="modal-body">
                                <ul>
                                    {% for message in messages %}
                                        <li>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div>
                <script type="text/javascript">
                    $('#message-modal').modal();
                </script>
                {% endif %}
            {% endblock base_messages %}
            {% block content %}{% endblock %}
        </div>
        {% block scripts %}{% endblock %}
    </body>
</html>

supervision/templates/supervision/delete.html
{% extends 'supervision/base.html' %}

{% block content %}
    <div class="container">
        <form role="form" class="form-signin" action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-5">
                    <h3>Delete item</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12"><p>Are you sure you want to delete "{{ object }}"?</p></div>
            </div>
            <div class="row">
                <div class="col-md-12"><button type="submit" class="btn btn-primary btn-block btn-lg">Confirm</button></div>
            </div>
        </form>
    </div>
{% endblock %}

supervision/templates/supervision/error.html
{% extends 'supervision/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1"><h2>Error</h2></div>
    </div>
    <div class="row">
        <div class="col-md-10 col-md-offset-1"><h4>{{ msg }}</h4></div>
    </div>
</div>
{% endblock %}

supervision/templates/supervision/home.html
{% extends 'supervision/base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>KANBAN-13</h1>
            <p>
                Kanban-13 is a kanban-based project tracking platform designed for developers,
                kanban masters and product owners.
            </p>
            <p>
                <a href="{% url 'boards:boards' %}" class="btn btn-primary btn-lg" role="button">Boards</a>
                <a href="{% url 'basic:documentation' %}" class="btn btn-primary btn-lg" role="button">Documentation</a>
            </p>
        </div>
    </div>
{% endblock %}

supervision/templates/supervision/login.html
{% extends 'supervision/base.html' %}

{% block content %}
    <div class="container">
        <form role="form" class="form-signin" action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.username.auto_id }}"><h4>Email</h4></label>
                <input type="text" id="{{ form.username.auto_id }}" name="{{ form.username.name }}" value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                       class="form-control" placeholder="Email" onfocus=""/>
            </div>
            <div class="form-group">
                <label for="{{ form.password.auto_id }}"><h4>Password</h4></label>
                <input type="password" id="{{ form.password.auto_id }}" name="{{ form.password.name }}" value="{% if form.password.value %}{{ form.password.value }}{% endif %}"
                       class="form-control" placeholder="Password" onfocus ="" />
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox"> Remember me
                </label>
            </div>
            <button type="submit" class="btn btn-primary btn-lg btn-block">Log in</button>
        </form>
        {% block base_messages %}{% endblock %}
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}