basic/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^documentation/$', views.DocumentationTemplateView.as_view(), name='documentation'),
)

kanban/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from supervision.views import LoginView, LogoutView, HomeView
import settings

admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
    url(r'^', include('basic.urls', namespace='basic')),
    url(r'^$', HomeView.as_view(), name='first_page'),
    url(r'^boards/', include('boards.urls', namespace='boards')),
    url(r'^supervision/', include('supervision.urls', namespace='supervision')),
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^analytics/', include('analytics.urls', namespace='analytics')),
    url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

supervision/urls.py
from django.conf.urls import patterns, url

import views


urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='home'),
)

# <editor-fold desc="User view urls">
urlpatterns += patterns('',
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/active/(?P<is_active>(True|False))/$', views.UserListView.as_view(),
        name='user_list'),
    url(r'^users/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^users/create/$', views.UserCreateView.as_view(), name='user_create'),
    url(r'^users/(?P<pk>\d+)/update/$', views.UserUpdateView.as_view(), name='user_update'),
    url(r'^users/(?P<pk>\d+)/delete/$', views.UserDeleteView.as_view(), name='user_delete'),
)
# </editor-fold>

# <editor-fold desc="Project view urls">
urlpatterns += patterns('',
    url(r'^projects/$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^projects/active/(?P<is_active>(True|False))/$', views.ProjectListView.as_view(),
        name='project_list'),
    url(r'^projects/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
    url(r'^projects/create/$', views.ProjectCreateView.as_view(), name='project_create'),
    url(r'^projects/(?P<pk>\d+)/update/$', views.ProjectUpdateView.as_view(),
        name='project_update'),
)
# </editor-fold>

# <editor-fold desc="Card view urls">
urlpatterns += patterns('',
    url(r'^cards/$', views.CardListView.as_view(), name='card_list'),
    url(r'^cards/active/(?P<is_active>(True|False))/$', views.CardListView.as_view(),
        name='card_list'),
    url(r'^cards/(?P<pk>\d+)/$', views.CardDetailView.as_view(), name='card_detail'),
    url(r'^cards/create/$', views.CardCreateView.as_view(), name='card_create'),
    url(r'^cards/(?P<pk>\d+)/update/$', views.CardUpdateView.as_view(), name='card_update'),
    url(r'^cards/(?P<pk>\d+)/delete/$', views.DeleteCardUpdateView.as_view(), name='card_delete'),
    url(r'^cards/move/(?P<pk>\d+)/$', views.MoveCardUpdateView.as_view(), name='card_move'),
)
# </editor-fold>

# <editor-fold desc="Team view urls">
urlpatterns += patterns('',
    url(r'^teams/$', views.TeamListView.as_view(), name='team_list'),
    url(r'^teams/active/(?P<is_active>(True|False))/$', views.TeamListView.as_view(),
        name='team_list'),
    url(r'^teams/(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^teams/create/$', views.TeamCreateView.as_view(), name='team_create'),
    url(r'^teams/(?P<pk>\d+)/update/$', views.TeamUpdateView.as_view(), name='team_update'),
)
# </editor-fold>

supervision/models.py
from django.db import models

# Create your models here.

supervision/forms/projects.py
from .base import StyledModelForm
from boards.config import DATE_FORMAT
from boards.models import Project, Team


class ProjectCreateForm(StyledModelForm):
    def __init__(self, user=None, *args, **kwargs):
        super(ProjectCreateForm, self).__init__(*args, **kwargs)

        self.fields['start_date'].widget.format = DATE_FORMAT
        self.fields['end_date'].widget.format = DATE_FORMAT
        self.fields['start_date'].input_formats = [DATE_FORMAT]
        self.fields['end_date'].input_formats = [DATE_FORMAT]

        self.fields['board'].queryset = user.boards_active
        self.fields['team'].queryset = Team.objects.filter(is_active=True)

    class Meta:
        model = Project


class ProjectUpdateForm(ProjectCreateForm):
    def __init__(self, *args, **kwargs):
        super(ProjectUpdateForm, self).__init__(*args, **kwargs)
        if self.instance.has_cards:
            self.fields['start_date'].widget.attrs['disabled'] = 'disabled'
            self.fields['is_active'].widget.attrs['disabled'] = 'disabled'

supervision/views/base.py
from django.http.response import HttpResponseRedirect
from django.http import Http404
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect

from braces.views import LoginRequiredMixin

from boards.config import GROUP_ADMINISTRATOR, GROUP_KANBAN_MASTER, GROUP_DEVELOPER, \
    GROUP_PRODUCT_OWNER
from boards.models import Project


class SetInactiveMixin(object):
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)


class FilterActiveMixin(object):
    def get_queryset(self):
        queryset = super(FilterActiveMixin, self).get_queryset()
        is_active = self.kwargs.get('is_active')

        if is_active is None:
            return queryset
        is_active = is_active == 'True'
        return queryset.filter(is_active=bool(is_active))


class NextPageMixin(object):
    def get_success_url(self):
        next_url = self.request.REQUEST.get('next')
        if next_url:
            return next_url

        return super(NextPageMixin, self).get_success_url()


class UserToFormKwargsMixin(object):
    def get_form_kwargs(self):
        kwargs = super(UserToFormKwargsMixin, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class PermissionsMixin(LoginRequiredMixin):
    """
    Checks, if logged in user is in required groups for provided project. Get project method has to
    be implemented, in order to retrieve project.
    This Mixin has to be the left most mixin in class based view (exception CsrfExemptMixin).
    """

    groups_required = []
    permission_denied_url = None

    def get_permission_denied_url(self):
        if not self.permission_denied_url:
            raise NotImplementedError('permission_denied_url_has_to_be_provided')

    def get_project(self):
        raise NotImplementedError('get_project method not implemented.')

    def get(self, request, *args, **kwargs):
        return self._validate() or super(PermissionsMixin, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self._validate() or super(PermissionsMixin, self).post(request, *args, **kwargs)

    def _validate(self):
        """Encapsulates validation in order not to repeat the code in get and post methods."""

        self._project = self.get_project()
        self._validate_input()

        # Checks if there are any queued messages.
        if self.request._messages._queued_messages:
            return redirect(self.get_permission_denied_url())

    def _validate_input(self):
        """
        If any addition permissions have to be checked, then this should be done in this method.
        """

        user, has_permission = self.request.user, False

        if GROUP_ADMINISTRATOR in self.groups_required:
            has_permission = has_permission or user.is_admin(self._project)
        if GROUP_KANBAN_MASTER in self.groups_required:
            has_permission = has_permission or user.is_kanban_master(self._project)
        if GROUP_PRODUCT_OWNER in self.groups_required:
            has_permission = has_permission or user.is_product_owner(self._project)
        if GROUP_DEVELOPER in self.groups_required:
            has_permission = has_permission or user.is_developer(self._project)

        if not has_permission:
            messages.info(self.request, 'Permission denied.')

supervision/views/cards.py
from django.http.response import Http404
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, CreateView, UpdateView

from .base import PermissionsMixin, FilterActiveMixin, UserToFormKwargsMixin
from ..forms import CardCreateModelForm, CardUpdateModelForm, CardDeleteModelForm, MoveCardModelForm
from boards.config import GROUP_PRODUCT_OWNER, GROUP_KANBAN_MASTER, GROUP_DEVELOPER
from boards.models import Card, Project
from boards.views import ShowBoardView, DEFAULT_CRITICAL_CARD_THRESHOLD


class CardAdminMixin(PermissionsMixin):
    """Checks if user has required permissions."""

    model = Card

    def get_project(self):
        if 'pk' in self.kwargs or 'slug' in self.kwargs:
            self.object = self.get_object()
            return self.object.project
        elif 'project_pk' in self.request.REQUEST:
            return get_object_or_404(Project, pk=self.request.REQUEST['project_pk'])
        else:
            raise Http404('Card or project id has to be provided.')

    def _validate_input(self):
        super(CardAdminMixin, self)._validate_input()

        if not self._project.board.has_columns:
            messages.info(self.request, "Project doesn't have active columns.")

    def get_permission_denied_url(self):
        return reverse('boards:show_board', args=(self._project.board.pk,))


class DataToFormKwargsMixin(UserToFormKwargsMixin):
    """Has to be placed left to ValidateInputMixin in order to have project."""

    def get_form_kwargs(self):
        kwargs = super(DataToFormKwargsMixin, self).get_form_kwargs()
        kwargs['project'] = self._project
        return kwargs


class CardDetailView(CardAdminMixin, DetailView):
    template_name = 'supervision/cards/detail.html'
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER, GROUP_DEVELOPER]


# Currently not used.
class CardListView(CardAdminMixin, FilterActiveMixin, ListView):
    template_name = 'supervision/cards/list.html'


class CardCreateView(CardAdminMixin, DataToFormKwargsMixin, CreateView):
    form_class = CardCreateModelForm
    template_name = 'supervision/cards/create.html'
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER]

    def _validate_input(self):
        """Kanban master adds cards to priority column, so it has to exist."""

        super(CardCreateView, self)._validate_input()
        if not self.request.user.is_kanban_master(self._project):
            return

        priority_column = self._project.board.priority_column
        if not priority_column:
            messages.info(self.request, 'Board doesnt have a priority column.')
        if priority_column.silver_bullet_cards.exists():
            messages.info(self.request, 'Priority column can only have 1 silver bullet card.')


class CardUpdateView(CardAdminMixin, DataToFormKwargsMixin, UpdateView):
    form_class = CardUpdateModelForm
    template_name = 'supervision/cards/update.html'
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER, GROUP_DEVELOPER]

    def _validate_input(self):
        super(CardUpdateView, self)._validate_input()

        self.object = self.get_object()
        if not self.object.can_update_card(self.request.user):
            messages.info(self.request, "You don't have permission to edit card in column "
                                        "%(column)s." % {'column': self.object.column})

    def get_form_kwargs(self):
        kwargs = super(CardUpdateView, self).get_form_kwargs()
        kwargs['card'] = self.object
        return kwargs


class DeleteCardUpdateView(CardAdminMixin, UserToFormKwargsMixin, UpdateView):
    form_class = CardDeleteModelForm
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER]

    def get(self, request, *args, **kwargs):
        raise Http404()

    def _validate_input(self):
        super(DeleteCardUpdateView, self)._validate_input()
        if not self.object.can_delete_card(self.request.user):
            messages.info(self.request, "You don't have permission to delete card.")
        if not self.object.is_active:
            messages.info(self.request, "Card is already deleted.")


class MoveCardUpdateView(CardAdminMixin, DataToFormKwargsMixin, UpdateView):
    form_class = MoveCardModelForm
    groups_required = [GROUP_KANBAN_MASTER, GROUP_PRODUCT_OWNER, GROUP_DEVELOPER]

    def get(self, request, *args, **kwargs):
        raise Http404()

    def form_invalid(self, form):
        return ShowBoardView().get(self.request, self.object.column.board.pk,
                                   critical_card_threshold=DEFAULT_CRITICAL_CARD_THRESHOLD,
                                   critical_card_error=False, form=form)

    def get_form_kwargs(self):
        kwargs = super(MoveCardUpdateView, self).get_form_kwargs()
        kwargs['card'] = self.object
        return kwargs

supervision/views/general.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from django.views.generic import View, TemplateView
from braces.views import LoginRequiredMixin

from supervision.forms.general import LoginForm


class LoginView(View):
    """
    View for login. Request parameter 'next' can contain the next page to render after login.
    """

    def get(self, request):
        if not request.user.is_authenticated():
            return render(request, 'supervision/login.html', {'form': LoginForm()})
        return render(request, 'supervision/home.html')

    def post(self, request):
        if not request.user.is_authenticated():
            form = LoginForm(data=request.POST)
            if form.is_valid():
                form.login_user(request)
            else:
                messages.warning(request, form.formatted_error)

        return redirect(request.REQUEST.get('next') or reverse('supervision:home'))


class LogoutView(View):
    """
    View for logout. Request parameter 'next' can contain the next page to render after logout.
    """

    def get(self, request):
        logout(request)
        return redirect(request.REQUEST.get('next') or reverse('supervision:home'))


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'supervision/home.html'


class ErrorView(LoginRequiredMixin, TemplateView):
    template_name = 'supervision/error.html'

supervision/views/projects.py
from django.views.generic import DetailView, ListView, CreateView, UpdateView

from braces.views import LoginRequiredMixin, GroupRequiredMixin

from .base import FilterActiveMixin, UserToFormKwargsMixin
from ..forms import ProjectCreateForm, ProjectUpdateForm
from boards.config import GROUP_KANBAN_MASTER
from boards.models import Project


class ProjectAdminMixin(LoginRequiredMixin, GroupRequiredMixin):
    model = Project
    group_required = GROUP_KANBAN_MASTER


class ProjectDetailView(ProjectAdminMixin, DetailView):
    template_name = 'supervision/projects/detail.html'


class ProjectListView(ProjectAdminMixin, FilterActiveMixin, ListView):
    context_object_name = 'projects'
    template_name = 'supervision/projects/list.html'


class ProjectCreateView(ProjectAdminMixin, UserToFormKwargsMixin, CreateView):
    form_class = ProjectCreateForm
    template_name = 'supervision/projects/create.html'


class ProjectUpdateView(ProjectAdminMixin, UserToFormKwargsMixin, UpdateView):
    form_class = ProjectUpdateForm
    template_name = 'supervision/projects/update.html'

    def get_form_kwargs(self):
        kwargs = super(ProjectUpdateView, self).get_form_kwargs()
        if 'data' in kwargs and self.object.has_cards:
            kwargs['data']._mutable = True
            kwargs['data']['start_date'] = self.object.start_date
            kwargs['data']['is_active'] = self.object.is_active

        return kwargs

supervision/views/users.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from braces.views import LoginRequiredMixin, GroupRequiredMixin

from .base import SetInactiveMixin, FilterActiveMixin
from ..forms import UserCreateForm, UserUpdateForm
from boards.config import GROUP_ADMINISTRATOR
from boards.models import User


class UserAdminMixin(LoginRequiredMixin, GroupRequiredMixin):
    model = User
    group_required = GROUP_ADMINISTRATOR


class UserDetailView(UserAdminMixin, DetailView):
    template_name = 'supervision/users/detail.html'


class UserListView(UserAdminMixin, FilterActiveMixin, ListView):
    context_object_name = 'users'
    template_name = 'supervision/users/list.html'


class UserCreateView(UserAdminMixin, CreateView):
    form_class = UserCreateForm
    template_name = 'supervision/users/create.html'


class UserUpdateView(UserAdminMixin, UpdateView):
    form_class = UserUpdateForm
    template_name = 'supervision/users/update.html'


class UserDeleteView(UserAdminMixin, SetInactiveMixin, DeleteView):
    template_name = 'supervision/delete.html'
    success_url = reverse_lazy('supervision:user_list')

supervision/templates/supervision/teams/base_form.html
{% extends 'supervision/base.html' %}

{% block content %}
    <div class="container">
        <form class="form-horizontal" method="post" role="form">
            {% csrf_token %}
            <h1 class="text-center">{% block title %}{% endblock title %}</h1>
                <br />
            <div class="row"><h4 class="col-md-8">General</h4></div>
            <div class="row form-group">
                    <label for="{{ form.name.auto_id }}" class="col-sm-3 control-label">
                        Team Name{% if form.name.field.required %}*{% endif %}
                    </label>
                    <div class="col-md-5 {% if form.name.errors %}has-error{% endif %}">
                        {% if form.name.errors %}
                            <label class="control-label" for="{{ form.name.auto_id }}">
                                {{ form.name.errors|striptags }}
                            </label>
                        {% endif %}
                        {{ form.name }}
                    </div>
            </div>
            {% block is_active_field %}
            {% endblock is_active_field %}
            <div class="row">
                <div class="col-md-12"><hr /></div>
            </div>
            <div class="row">
                <div class="col-md-6"><h4>Team members</h4></div>
                <div class="col-md-2 col-md-offset-2">
                </div>
            </div>
            <table class="member-container table table-hover col-md-offset-1">
                        {{ formset.management_form }}
                        <tr class="row">
                            <th class="col-md-4">User</th>
                            <th class="col-md-4">Role</th>
                            <th class="col-md-1">Active</th>
                            <th class="col-md-1">
                                <a href="#" class="btn btn-default add-user">Add Member</a>
                            </th>
                        </tr>
                        {% for user_form in formset %}
                            <tr id="user-{{ forloop.counter0 }}" class="row">

                                {{ user_form.id }}
                                <td class="col-md-4 user form-group">{{ user_form.user }}</td>
                                <td class="col-md-4 group">{{ user_form.group }}</td>
                                <td class="col-md-1">{{ user_form.is_active }}</td>
                            </tr>
                        {% endfor %}
            </table>
            <hr />
            <div class="row">
                <div class="col-md-10">
                    {% for key, value in form.errors.items %}
                        {{ value }}
                    {% endfor %}
                    {% for error in formset.non_form_errors %}
                        {{ error }}
                    {% endfor %}
                    {% for error in formset.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>
            <br />
            <div class="row">
                <button type="submit" class="btn btn-primary btn-lg">{% block btn_caption %}{% endblock %}</button>
            </div>
       </form>
    </div>

<script type="text/html" id="member-template">
    <tr id="user-<%= id %>" class="row">
        <td class="col-md-4 user"><select class="form-control" id="id_userteam_set-<%= id %>-user" name="userteam_set-<%= id %>-user">
        </select></td>
        <td class="col-md-4 group"><select class="form-control" id="id_userteam_set-<%= id %>-group" name="userteam_set-<%= id %>-group"><option> ------- </option></select></td>
        <td class="col-md-1"><input class="form-control" id="id_userteam_set-<%= id %>-is_active" name="userteam_set-<%= id %>-is_active" type="checkbox" checked="checked"></td>
        <input type="hidden" id="id_userteam_set-<%= id %>-id" name="userteam_set-<%= id %>-id" />
    </tr>
</script>
<script type="text/html" id="user-set"></script>
{% endblock %}

{% block scripts %}
    {% load staticfiles %}
    <script src="{% static 'supervision/js/underscore-min.js' %}"></script>
    <script src="{% static 'supervision/js/teams/team.create.js' %}"></script>
{% endblock %}

supervision/templates/supervision/teams/create.html
{% extends 'supervision/teams/base_form.html' %}


{% block title %}Create Team{% endblock %}
{% block btn_caption %}Create{% endblock %}

supervision/templates/supervision/teams/detail.html
{% extends 'supervision/base.html' %}

{% block content %}
    <div class="container">
        <div class="row"><h4 class="col-md-8">General</h4></div>
        <div class="row col-md-offset-2">
            <div class="col-md-2"><b>Name</b></div>
            <div class="col-md-8">{{ team.name }}</div>
            <div class="col-md-2">
                {% if user.can_be_kanban_master %}

                    <a href="{% url 'supervision:team_update' team.pk %}"
                       type="button" class="btn btn-primary btn-block">Edit</a>
                {% else %}
                    <br />
                {% endif %}
            </div>
        <div class="row col-md-offset-0">
            <div class="col-md-2"><b>Active</b></div>
            <div class="col-md-8">
                {% if object.is_active %}
                    <span class="glyphicon glyphicon-ok"></span>
                {% else %}
                    <span class="glyphicon glyphicon-remove"></span>
                {% endif %}
            </div>
            <div class="col-md-2"></div>
        </div>
        </div>
        <div class="row">
            <div class="col-md-12"><hr /></div>
        </div>
        <div class="row">
            <div class="col-md-6"><h4>Team members</h4></div>
        </div>
        <div class="row col-md-offset-2">
            {% if team.users|length > 0 %}
            <table class="table table-hover">
                <tr>
                    <th class="col-md-4">Username</th>
                    <th class="col-md-3">Name</th>
                    <th class="col-md-3">Surname</th>
                    <th class="col-md-4">Role</th>
                </tr>
            {% for ut in team.userteam_set.all %}
                {% if ut.is_active %}
                <tr>
                    <td class="col-md-4">{{ ut.user.email }}</td>
                    <td class="col-md-3">{{ ut.user.first_name }}</td>
                    <td class="col-md-3">{{ ut.user.last_name }}</td>
                    <td class="col-md-4">{{ ut.group.name }}</td>
                </tr>
                {% endif %}
            {% endfor %}
            </table>
            {% else %}
            <div class="md-12"><h3>This team has no users</h3></div>
            {% endif %}
        </div>
    </div>
{% endblock %}

supervision/templates/supervision/teams/list.html
{% extends 'supervision/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-10">
                    <h1 class="text-center">Teams</h1>
                </div>
            </div>
            {% if user.can_be_kanban_master %}
            <p class="text-right">
                <a href="{% url 'supervision:team_create' %}" type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus"></span> Create Team
                </a>
            </p>
            {% endif  %}
            <div class="row">
                <div class="col-md-10">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Is Active</th>
                                <th style="width: 60px"></th>
                                <th style="width: 60px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in teams %}
                            <tr>
                                <td>{{ object.pk }}</td>
                                <td>{{ object.name }}</td>
                                <td>
                                    {% if object.is_active %}
                                        <span class="glyphicon glyphicon-ok"></span>
                                    {% else %}
                                        <span class="glyphicon glyphicon-remove"></span>
                                    {% endif %}
                                </td>
                                <td><a href="{% url 'supervision:team_detail' pk=object.pk %}">Details</a></td>

                                {% if user.can_be_kanban_master %}
                                    <td><a href="{% url 'supervision:team_update' pk=object.pk %}">Update</a></td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-md-2">
                    <table class="table table-filter">
                        <thead>
                            <tr><th>&nbsp;</th></tr>
                        </thead>
                        <tbody>
                            <tr><th class="bg-info">Filter by active</th></tr>
                            <tr><td><a href="{% url 'supervision:team_list' %}">All</a></td></tr>
                            <tr><td><a href="{% url 'supervision:team_list' is_active=True %}">Yes</a></td></tr>
                            <tr><td><a href="{% url 'supervision:team_list' is_active=False %}">No</a></td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

supervision/templates/supervision/teams/update.html
{% extends 'supervision/teams/base_form.html' %}

{% block title %}Update Team{% endblock title %}
{% block is_active_field %}
<div class="form-group row">
        <label for="{{ form.is_active.auto_id }}" class="col-sm-3 control-label">Is Active{% if form.is_active.field.required %}*{% endif %}</label>
        <div class="col-md-1 {% if form.is_active.errors %}has-error{% endif %}">
            {% if form.is_active.errors %}
                <label class="control-label" for="{{ form.is_active.auto_id }}">
                    {{ form.is_active.errors|striptags }}
                </label>
            {% endif %}
            {{ form.is_active }}

        </div>
</div>
{% endblock is_active_field %}
{% block btn_caption %}Save{% endblock btn_caption%}