analytics/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.ChooseAnalyticsView.as_view(), name='choose'),
    url(r'^cumulative/choose$', views.CumulativeFlowView.as_view(), name='cumulative_choose'),
    url(r'^cumulative/board_selected$', views.CumulativeProjectsView.as_view(),
        name='cumulative_board_selected'),
    url(r'^cumulative/show$', views.CumulativeFlowView.as_view(), name='cumulative_show'),
    url(r'^wip_violations/choose$', views.WipViolationsView.as_view(), name='wip_choose'),
    url(r'^wip_violations/board_selected$', views.WipViolationsProjectsView.as_view(),
        name='wip_board_selected'),
    url(r'^wip_violations/show$', views.WipViolationsView.as_view(), name='wip_violations_show'),
    url(r'^dev_contribution/choose', views.DeveloperContributionView.as_view(), name='developer_contribution_choose'),
    url(r'^dev_contribution/show$', views.DeveloperContributionView.as_view(), name='developer_contribution'),
    url(r'^dev_contribution/board_selected$', views.DeveloperContributionProjectsView.as_view(),
        name='dev_contr_board_selected'),
    url(r'^average_lead_time/show$', views.AverageLeadTimeView.as_view(),
        name='average_lead_time_show'),
    url(r'^average_lead_time/choose$', views.AverageLeadTimeChooseView.as_view(),
        name='average_lead_time_choose'),
    url(r'^average_lead_time/choose_end$', views.AverageLeadTimeChooseEndView.as_view(),
        name='average_lead_time_choose_end'),
    url(r'^average_lead_time/board_selected$', views.AverageLeadTimeSelectView.as_view(),
        name='average_lead_time_selected'),
)

basic/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^documentation/$', views.DocumentationTemplateView.as_view(), name='documentation'),
)

kanban/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from supervision.views import LoginView, LogoutView, HomeView
import settings

admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
    url(r'^', include('basic.urls', namespace='basic')),
    url(r'^$', HomeView.as_view(), name='first_page'),
    url(r'^boards/', include('boards.urls', namespace='boards')),
    url(r'^supervision/', include('supervision.urls', namespace='supervision')),
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^analytics/', include('analytics.urls', namespace='analytics')),
    url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

analytics/models.py
from django.db import models

# Create your models here.

analytics/views.py
import datetime
import time
import unicodedata
from itertools import chain

from django.views.generic import View
from django.shortcuts import render, get_object_or_404, redirect

from braces.views import LoginRequiredMixin

from boards.models import Board, Project, Card, CardHistory, User, UserTeam
from utils import get_cards_subset


class ChooseBoardMixin(object):
    def _get_boards(self, user):
        boards = Board.objects.filter(is_active=True, author=user)
        return boards

    def post(self, request):
        board_id = request.POST['board']
        context = {}
        boards = self._get_boards(request.user)

        context['boards'] = boards
        if board_id:
            board = get_object_or_404(Board, pk=board_id)
            projects = Project.objects.filter(is_active=True, board_id=board_id)
            context['selected_board'] = board
            context['projects'] = projects

        return render(request, self.template, context)


class AnalyticsBaseMixin(object):
    def get(self, request):
        context = {}
        boards = self._get_boards(request.user)

        context['boards'] = boards
        return render(request, self.template, context)

    def _get_boards(self, user):
        boards = Board.objects.filter(is_active=True, author=user)
        return boards

    def _get_columns_list(self, board):
        columns_list = []
        col = board.first_column
        if col:
            while col:
                columns_list.append(col)
                if col.has_children():
                    children = col.get_all_children
                    for child in children:
                        columns_list.append(child)
                col = col.next_column
        return columns_list

    def _get_col_dict_from_list(self, col_list):
        dict = {}
        for i in range(len(col_list)):
            dict[col_list[i].name] = i
        return dict


class ChooseAnalyticsView(LoginRequiredMixin, View):
    def get(self, request):

        return render(request, 'analytics/analytics.html')


class CumulativeProjectsView(ChooseBoardMixin, LoginRequiredMixin, View):
    """
    Board is chosen and projects need to be filtered
    """

    template = 'analytics/choose_cumulative.html'


class CumulativeFlowView(AnalyticsBaseMixin, LoginRequiredMixin, View):
    template = 'analytics/choose_cumulative.html'

    def post(self, request):
        board_id = request.POST['selected_board']
        #date_from = datetime.datetime(2014, 5, 5)
        date_from = None
        date_to = datetime.datetime.now()
        context = {}
        boards = self._get_boards(request.user)
        context['boards'] = boards
        if request.POST.get('start_date'):
            date_from = request.POST.get('start_date')
            context['date_from'] = date_from
            date_from = time.strptime(date_from, "%d.%m.%Y")
            date_from = datetime.datetime.fromtimestamp(time.mktime(date_from))
        else:
            context['start_date_error'] = True
            board = get_object_or_404(Board, pk=board_id)
            projects = Project.objects.filter(is_active=True, board=board)
            context['selected_board'] = board
            context['projects'] = projects
            return render(request, self.template, context)

        if request.POST.get('end_date'):
            date_to = request.POST.get('end_date')
            context['date_to'] = date_to
            date_to = time.strptime(date_to, "%d.%m.%Y")
            date_to = datetime.datetime.fromtimestamp(time.mktime(date_to))

        if date_to > datetime.datetime.now():
            date_to = datetime.datetime.now()
        date_difference = date_to - date_from + datetime.timedelta(days=1)
        #print date_from, date_to, date_difference
        if date_difference <= datetime.timedelta(days=0):
            context['end_date_error'] = True
            board = get_object_or_404(Board, pk=board_id)
            projects = Project.objects.filter(is_active=True, board=board)
            context['selected_board'] = board
            context['projects'] = projects
            return render(request, self.template, context)

        if board_id:
            board = get_object_or_404(Board, pk=board_id)
            projects = Project.objects.filter(is_active=True, board=board)
            context['selected_board'] = board
            context['projects'] = projects

            # get selected project and make query for cards
            if request.POST['project']:
                project_id = request.POST['project']
                if str(project_id) != 'all':
                    selected_project = get_object_or_404(Project, pk=project_id)
                    context['selected_project'] = selected_project
                    projects = [selected_project]

            #cards = Card.objects.filter(is_active=True, project__in=projects)
            cards = Card.objects.filter(project__in=projects)

            if not cards:
                context['no_cards'] = True
                return render(request, self.template, context)

            # get cards subset - 3 different intervals, size and type
            cards, context = get_cards_subset(request.POST, cards, context)

            # check which columns subset is selected
            # possible: only children columns or all columns
            children_cols_only = True
            if request.POST.get('columns_subset'):
                cols_subset = request.POST.get('columns_subset')
                if str(cols_subset) == 'all':
                    children_cols_only = False
                    context['allcols_selected'] = True

            if children_cols_only:
                columns = self._get_columns_list_children(board)
            else:
                columns = self._get_columns_list(board)

            columns_dict = self._get_col_dict_from_list(columns)  # lookup table for column indexes

            matrix = [[0 for _ in range(date_difference.days)] for _ in columns]

            attributes = [CardHistory.ACTION_CARD_CREATED, CardHistory.ACTION_CARD_MOVED,
                          CardHistory.ACTION_CARD_WIP_VIOLATION]

            for card in cards:
                card_history = CardHistory.objects.filter(card=card, action__in=attributes)
                if card_history.count() > 0:
                    first_history = card_history.filter(time_created__lte=date_from)
                    if first_history:
                        first_history = first_history.first()
                    else:
                        first_history = card_history.last()
                    card_history = card_history.filter(time_created__gte=first_history.time_created)\
                        .reverse()
                    for i in range(card_history.count()):
                        ch = card_history[i]
                        col_i = columns_dict[ch.column_to.name]
                        if i < card_history.count() - 1:
                            ch_next = card_history[i + 1]
                            matrix = self._increment_days(col_i, ch.time_created,
                                                          ch_next.time_created, matrix,
                                                          date_from)
                            if not children_cols_only and ch.column_to.parent_column:
                                parent_col_i = columns_dict[ch.column_to.parent_column.name]
                                matrix = self._increment_days(parent_col_i, ch.time_created,
                                                              ch_next.time_created, matrix,
                                                              date_from)
                        else:
                            date_to = None
                            # check if card was deleted
                            card_history_deleted = CardHistory.objects.filter(card=card,
                                                            action=CardHistory.ACTION_CARD_DELETED)
                            if card_history_deleted.count() > 0:
                                deleted = card_history_deleted.first()
                                if deleted.time_created > ch.time_created:
                                    date_to = deleted.time_created

                            matrix = self._increment_days(col_i, ch.time_created,
                                                          date_to, matrix, date_from)
                            if not children_cols_only and ch.column_to.parent_column:
                                parent_col_i = columns_dict[ch.column_to.parent_column.name]
                                matrix = self._increment_days(parent_col_i, ch.time_created,
                                                              date_to, matrix, date_from)

            """
            print columns_dict
            # print matrix:
            for line in matrix:
                for el in line:
                    print el,
                print ''
            """
            # create matrix to show in google charts on template
            data = [[0 for _ in range(len(matrix)+1)] for _ in range(len(matrix[0])+1)]
            data[0][0] = "Date"
            # modifiy columns order
            for i in range(len(columns)):
                data[0][i+1] = str(columns[len(columns)-1-i].name)
            for i in range(len(data)-1):
                data[i+1][0] = str((date_from + datetime.timedelta(days=i)).date())
            # copy data from matrix in right order
            for i in range(len(data)-1):
                for j in range(len(data[i])-1):
                    data[i+1][j+1] = matrix[len(matrix)-1-j][i]
            """
            # print data matrix:
            for line in data:
                for el in line:
                    print el,
                print ''
            """
            context['graph_data'] = data

            return render(request, self.template, context)

analytics/templates/analytics/analytics.html
{% extends 'supervision/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <h1 class="text-center">Analytics</h1>
        </div>
    </div>

    <div class="row">
        <div>
            <ul>
                {% if user.can_be_kanban_master %}
                    <li>
                        <a href="{% url 'analytics:cumulative_choose' %}">
                            Cumulative flow diagram</a>
                    </li>
                    <li>
                        <a href="{% url 'analytics:average_lead_time_show' %}">
                        Average lead time
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'analytics:developer_contribution_choose' %}">
                            Developer contribution
                        </a>
                    </li>
                {% endif %}

                <li>
                    <a href="{% url 'analytics:wip_choose' %}">
                        Wip violations list</a>
                </li>
            </ul>
        </div>
    </div>
</div>


{% endblock %}

analytics/templates/analytics/average_lead_time.html
{% extends 'supervision/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h1 class="text-center">Average lead time</h1>
            </div>
        </div>

        <div class="row">
            <form class="form-horizontal" role="form" action="{% url 'analytics:average_lead_time_selected' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                    <label for="board_id2" class="col-sm-2 control-label">
                        Board
                    </label>

                    <div class="col-sm-3">
                        <select id="board_id2" name="board" class="form-control" onChange="this.form.submit();">
                            <option value="">----</option>
                            {% for b in boards %}
                                <option value="{{ b.id }}"
                                        {% if selected_board.id == b.id %}
                                        selected="selected"
                                        {% endif %}>
                                    {{ b.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </form>
        </div>

        {% if selected_board %}
            <div class="row">
            <form class="form-horizontal" role="form" action="{% url 'analytics:average_lead_time_choose' %}"
              method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="start_column_id" class="col-sm-2 control-label">
                        Start column
                    </label>

                    <div class="col-sm-3">
                        <select id="start_column_id" name="start_column" class="form-control" onChange="this.form.submit();">
                            {% if not start_columns %}
                                <option value="">----</option>
                            {% else %}
                                <option value="all">All columns</option>
                                {% for c in start_columns %}
                                    <option value="{{ c.id }}"
                                            {% if selected_start_column.id == c.id %}
                                            selected="selected"
                                            {% endif %}>
                                        {{ c.name }}</option>
                                {% endfor %}
                            {% endif %}
                        </select>
                    </div>
                    <input type="hidden" name="board" value="{{ selected_board.id }}" />
                </div>
            </form>
            </div>

            <div class="row">
                <form class="form-horizontal" role="form" action="{% url 'analytics:average_lead_time_choose_end' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="stop_column_id" class="col-sm-2 control-label">
                        Stop column
                    </label>

                    <div class="col-sm-3">
                        <select id="stop_column_id" name="stop_column" class="form-control" onChange="this.form.submit();">
                            {% if not end_columns %}
                                <option value="">----</option>
                            {% else %}
                                <option value="all">All columns</option>
                                {% for c in end_columns %}
                                    <option value="{{ c.id }}"
                                            {% if selected_end_column.id == c.id %}
                                            selected="selected"
                                            {% endif %}>
                                        {{ c.name }}</option>
                                {% endfor %}
                            {% endif %}
                        </select>
                    </div>
                    <input type="hidden" name="selected_board" value="{{ selected_board.id }}" />
                    <input type="hidden" name="selected_start_column" value="{{ selected_start_column.id }}" />
                </div>
                </form>
            </div>


            <div class="row">
                <form class="form-horizontal" role="form" action="{% url 'analytics:average_lead_time_show' %}"
                      method="POST">
                    {% csrf_token %}
                    {% include 'analytics/average_lead_time_card_subset.html' %}


                    <input type="hidden" name="selected_board" value="{{ selected_board.id }}" />
                    <input type="hidden" name="selected_start_column" value="{{ selected_start_column.id }}" />
                    <input type="hidden" name="selected_end_column" value="{{ selected_end_column.id }}" />
                    <div class="form-group">
                        <button type="submit" class="btn btn-default margin-left-30">Draw</button>
                    </div>
                </form>
            </div>
        {% endif %}


        {% if no_cards %}
        <div class="warning-font">
            There is no cards yet on this board.
        </div>
        {% endif %}

        {% if error %}
        <div class="warning-font">
            No data to display.
        </div>
        {% endif %}

        {% if graph_data %}
            <div class="row">
                <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#show-cards-dit">
                                    Details
                                </a>
                            </h4>
                        </div>
                        <div id="show-cards-dit" class="panel-collapse collapse">
                            <div class="panel-body">
                                <ul>
                                    {% for el in sum %}
                                       <li>{{ el.0 }} : {{ el.1 }} days </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div id="cum_flow" class="cumulative-flow-style"></div>
            </div>
        {% endif %}

        <div style="height: 50px"></div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <link rel="stylesheet" href="{% static 'supervision/css/datepicker.css' %}" />
    <script type="text/javascript" src="{% static 'supervision/js/bootstrap-datepicker.js' %}"></script>

    <script type="text/javascript">
        google.load("visualization", "1", {packages: ["corechart"]});
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                {% autoescape off %}
                    {% for line in graph_data %}
                        {{ line }},
                    {% endfor %}
                {% endautoescape %}
            ]);

            /*var data = google.visualization.arrayToDataTable([
              ['Card id', 'Analysis & Design', 'Coding', 'Testing', 'Integration', 'Documentation', 'Acceptance Ready', 'Acceptance', 'Average'],
              ['1',  2.7,      7,         0,             8.8,           1.3,      0,    1.3, 22],
              ['2',  2.7,      7,         0,             8.8,           1.3,      0,    1.3, 22],
              ['3',  2.7,      7,         0,             8.8,           1.3,      0,    1.3, 22],
              ['4',  2.7,      7,         0,             8.8,           1.3,      0,    1.3, 22],
              ['5',  2.7,      7,         0,             8.8,           1.3,      0,    1.3, 22],
            ]);*/

            var options = {
                title : 'Average lead time',
                vAxis: {title: "Time (days)"},
                hAxis: {title: "Card names"},
                seriesType: "bars",
                {% comment %}series: { {{ avg_attr_index }} : {type: "line"}}, {% endcomment %}
                isStacked: true
            };

            var chart = new google.visualization.ComboChart(document.getElementById('cum_flow'));
            chart.draw(data, options);
        }

        $(document).ready(function() {
            var dateFormat = {'format': 'dd.mm.yyyy'};
            $('#start_created_id').datepicker(dateFormat);
            $('#end_created_id').datepicker(dateFormat);

            $('#start_done_id').datepicker(dateFormat);
            $('#end_done_id').datepicker(dateFormat);

            $('#start_development_id').datepicker(dateFormat);
            $('#end_development_id').datepicker(dateFormat);
        });
    </script>

{% endblock %}

analytics/templates/analytics/choose_cumulative.html
{% extends 'supervision/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h1 class="text-center">Cumulative flow diagram</h1>
            </div>
        </div>

        <div class="row">
            <form class="form-horizontal" role="form" action="{% url 'analytics:cumulative_board_selected' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                    <label for="board_id2" class="col-sm-2 control-label">
                        Board
                    </label>

                    <div class="col-sm-3">
                        <select id="board_id2" name="board" class="form-control" onChange="this.form.submit();">
                            <option value="">----</option>
                            {% for b in boards %}
                                <option value="{{ b.id }}"
                                        {% if selected_board.id == b.id %}
                                        selected="selected"
                                        {% endif %}>
                                    {{ b.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

            </form>
        </div>

        {% if selected_board %}
            <div class="row">
                <form class="form-horizontal" role="form" action="{% url 'analytics:cumulative_show' %}"
                      method="POST">
                    {% csrf_token %}
                    {% include 'analytics/card_subset_form.html' %}

                    <div class="form-group">
                        <label for="columns" class="col-sm-2 control-label">
                            Show columns
                        </label>

                        <div class="col-sm-3">
                            <select id="columns" name="columns_subset" class="form-control">
                                <option value="subcols">
                                    Just sub-columns</option>
                                <option value="all" {% if allcols_selected %}selected="selected"{% endif %}>
                                    All columns</option>
                            </select>
                        </div>
                    </div>

                    <input type="hidden" name="selected_board" value="{{ selected_board.id }}" />
                    <div class="form-group">
                        <button type="submit" class="btn btn-default margin-left-30">Draw</button>
                    </div>
                </form>
            </div>
        {% endif %}


        {% if no_cards %}
        <div class="warning-font">
            There is no cards yet on this board.
        </div>
        {% endif %}

        {% if graph_data %}
            <div class="row">
                <div id="cum_flow" class="cumulative-flow-style"></div>
            </div>
        {% endif %}

        <div style="height: 50px"></div>

    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <link rel="stylesheet" href="{% static 'supervision/css/datepicker.css' %}" />
    <script type="text/javascript" src="{% static 'supervision/js/bootstrap-datepicker.js' %}"></script>

    <script type="text/javascript">
        google.load("visualization", "1", {packages: ["corechart"]});
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                {% autoescape off %}
                    {% for line in graph_data %}
                        {{ line }},
                    {% endfor %}
                {% endautoescape %}
            ]);

            var options = {
                title: 'Cumulative Flow diagram',
                legend: {
                    position: 'right'
                },
                chartArea: {
                    left: 50
                },
                pointSize: 5,
                isStacked: true
            };

            var chart = new google.visualization.AreaChart(document.getElementById('cum_flow'));
            chart.draw(data, options);
        }

        $(document).ready(function() {
            var dateFormat = {'format': 'dd.mm.yyyy'};
            $('#start_date_id').datepicker(dateFormat);
            $('#end_date_id').datepicker(dateFormat);

            $('#start_created_id').datepicker(dateFormat);
            $('#end_created_id').datepicker(dateFormat);

            $('#start_done_id').datepicker(dateFormat);
            $('#end_done_id').datepicker(dateFormat);

            $('#start_development_id').datepicker(dateFormat);
            $('#end_development_id').datepicker(dateFormat);
        });
    </script>

{% endblock %}